//CONST VALUES
const noiseDescriptions = {
    0: {
        title: "White Noise",
        description: "Equal energy at every frequency. Power spectral density is flat across the entire spectrum. Generated by sampling independent Gaussian random variables."
    },
    1: {
        title: "Pink Noise",
        description: "Power spectral density falls as 1/f — each octave carries equal energy. Ubiquitous in nature: heartbeats, river flows, electronic components."
    },
    2: {
        title: "Brown Noise",
        description: "Power spectral density falls as 1/f² — equivalent to integrating white noise. Resembles a random walk. Deep, rumbling character with strong low frequency content."
    },
    3: {
        title: "Blue Noise",
        description: "Power spectral density rises linearly with frequency — the spectral complement of pink noise. Higher frequencies dominate, producing a bright, hiss-like character."
    }
};

const serverURL = "https://noisegenerator.onrender.com";
//const serverURL = "http://localhost:5000";

//Configurable Variables
const state = {
    noiseType : 0,
    samplingRate : 44100,
    volume : 50,
    duration : 5
};

//Response Variables
let audioData = null;

//Audio Playback
const waveformCanvas = document.getElementById('waveformDisplay');
const waveformCtx = waveformCanvas.getContext('2d');
waveformCanvas.width = waveformCanvas.offsetWidth;
waveformCanvas.height = waveformCanvas.offsetHeight;

const spectrogramCanvas = document.getElementById('spectrogramDisplay');
const spectrogramCtx = spectrogramCanvas.getContext('2d');
spectrogramCanvas.width = spectrogramCanvas.offsetWidth;
spectrogramCanvas.height = spectrogramCanvas.offsetHeight;

const audioContext = new AudioContext();
const gainNode = audioContext.createGain();
const analyserNode = audioContext.createAnalyser();
let source = null;
analyserNode.fftSize = 2048;

const audioPlaybackSlider = document.getElementById('audioPlaybackSlider')
let startTime = 0;
let startOffset = 0;
let pauseTime = 0;
let isPlaying = false;
let isClickingAudio = false;

const waveformBufferLength = analyserNode.fftSize;
const waveformData = new Uint8Array(waveformBufferLength);

const spectrogramBufferLength = analyserNode.frequencyBinCount;
const spectrogramData = new Uint8Array(spectrogramBufferLength);

//AP - Controls
const audioPlaybackStopBtn = document.getElementById("audioPlaybackStopBtn");
const audioPlaybackPauseBtn = document.getElementById("audioPlaybackPauseBtn");
const audioPlaybackPlayBtn = document.getElementById("audioPlaybackPlayBtn");

audioPlaybackStopBtn.addEventListener('click', function () {
    stopAudio(true);
});

audioPlaybackPauseBtn.addEventListener('click', function () {
    stopAudio();
});

audioPlaybackPlayBtn.addEventListener('click', function () {
    if(audioData == null) {
        return;
    }

    playAudio(audioData.samples, audioData.samplingRate, pauseTime);
});

audioPlaybackSlider.addEventListener('mousedown', function() {
    if(audioData == null) {
        return;
    }

    isClickingAudio = true;
    if(isPlaying) {
        stopAudio();
    }
});

audioPlaybackSlider.addEventListener('mouseup', function() {
    if(audioData == null) {
        return;
    }

    pauseTime = parseFloat(audioPlaybackSlider.value);
    playAudio(audioData.samples, audioData.samplingRate, pauseTime);

    isClickingAudio = false;
});

function playbackDraw() {
    if(isPlaying && !isClickingAudio) {
        const position = startOffset + (audioContext.currentTime - startTime);
        audioPlaybackSlider.value = position;
    }
}

async function stopAudio(reset=false) {
    if(source == null) {
        return;
    }

    if(reset){
        pauseTime = 0;
        audioPlaybackSlider.value = 0;
    } else {
        pauseTime = startOffset + (audioContext.currentTime - startTime);
    }

    source.stop();
    isPlaying = false;
}

async function playAudio(samples, samplingRate, offset=0) {
    const buffer = audioContext.createBuffer(1, samples.length, parseInt(samplingRate));
    const channelData = buffer.getChannelData(0);
    for(let i = 0; i < samples.length; i++) {
        channelData[i] = samples[i];
    }

    source = audioContext.createBufferSource();
    source.buffer = buffer;

    //routing
    source.connect(analyserNode);
    analyserNode.connect(gainNode);
    gainNode.connect(audioContext.destination);

    source.start(0, offset);
    startTime = audioContext.currentTime;
    startOffset = offset;
    isPlaying = true;
}

//AP - Generate
const generateNoiseBtn = document.getElementById("generateNoiseBtn");
generateNoiseBtn.addEventListener('click', async function() {
    await generateNoise();
});

async function generateNoise() {
    try {
        const response = await fetch(serverURL + "/api/noise", {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(state)
        });

        const data = await response.json();

        audioData = data;
        if (audioContext.state === 'suspended') {
            audioContext.resume();
        }

        audioPlaybackSlider.max = data.duration;
        audioPlaybackSlider.value = 0;
        pauseTime = 0;
        playAudio(audioData.samples, audioData.samplingRate);
    } catch(error) {
        console.error("[ERROR] Could not generate audio noise:", error);
    }
}

//Waveform
function waveformDraw() {
    const WIDTH = waveformCanvas.width;
    const HEIGHT = waveformCanvas.height;

    analyserNode.getByteTimeDomainData(waveformData);

    waveformCtx.fillStyle = "rgb(183, 183, 183)";
    waveformCtx.fillRect(0, 0, WIDTH, HEIGHT);
    waveformCtx.lineWidth = 1;
    waveformCtx.strokeStyle = "rgb(131, 144, 250)";

    const sliceWidth = (WIDTH * 1.0) / waveformBufferLength;
    let x = 0;

    waveformCtx.beginPath();
    for (let i = 0; i < waveformBufferLength; i++) {
        const v = waveformData[i] / 128.0;
        const y = (v * HEIGHT) / 2;

        if (i === 0) {
        waveformCtx.moveTo(x, y);
        } else {
        waveformCtx.lineTo(x, y);
        }

        x += sliceWidth;
    }

    waveformCtx.lineTo(WIDTH, HEIGHT / 2);
    waveformCtx.stroke();
}

//Spectrogram
function heatMapColor(amplitude) {
    let r, g, b;
    
    if(amplitude < 64) {
        // black to blue
        r = 0;
        g = 0;
        b = Math.round((amplitude / 63) * 255);
    } else if(amplitude < 128) {
        // blue to red
        const t = (amplitude - 64) / 63;
        r = Math.round(t * 255);
        g = 0;
        b = Math.round((1 - t) * 255);
    } else if(amplitude < 192) {
        // red to yellow
        const t = (amplitude - 128) / 63;
        r = 255;
        g = Math.round(t * 255);
        b = 0;
    } else {
        // yellow to white
        const t = (amplitude - 192) / 63;
        r = 255;
        g = 255;
        b = Math.round(t * 255);
    }
    
    return `rgb(${r}, ${g}, ${b})`;
}

function getRMSVolume() {
    analyserNode.getByteTimeDomainData(waveformData);
    let sumSquares = 0;
    for(let i = 0; i < waveformBufferLength; i++) {
        const normalized = (waveformData[i] / 128.0) - 1;
        sumSquares += normalized * normalized;
    }
    return Math.sqrt(sumSquares / waveformBufferLength);
}

function spectrogramDraw() {
    const WIDTH = spectrogramCanvas.width;
    const HEIGHT = spectrogramCanvas.height;

    analyserNode.getByteFrequencyData(spectrogramData);

    spectrogramCtx.drawImage(spectrogramCanvas, -1, 0);

    for(let i = 0; i < spectrogramBufferLength; i++) {
        const amplitude = spectrogramData[i];
        const y = Math.round((1 - i/spectrogramBufferLength) * HEIGHT);
        const binHeight = Math.ceil(HEIGHT / spectrogramBufferLength);

        //color
        spectrogramCtx.fillStyle = heatMapColor(amplitude);
        spectrogramCtx.fillRect(WIDTH - 1, y, 1, binHeight);
    }
}

//Noise Button Selections
const whiteNoiseBtn = document.getElementById("whiteNoiseBtn");
const pinkNoiseBtn = document.getElementById("pinkNoiseBtn");
const brownNoiseBtn = document.getElementById("brownNoiseBtn");
const blueNoiseBtn = document.getElementById("blueNoiseBtn");
const descriptionTitle = document.getElementById('descriptionTitle');
const descriptionText = document.getElementById('descriptionText');


const noiseBtns = [whiteNoiseBtn, pinkNoiseBtn, brownNoiseBtn, blueNoiseBtn];
for(let i = 0; i < noiseBtns.length; i++) {
    noiseBtns[i].addEventListener('click', function() {
        SetNoiseSelection(i);
    });
}

function SetNoiseSelection(index) {
    state.noiseType = index;

    for(let i = 0; i < noiseBtns.length; i++) {
        noiseBtns[i].classList.remove("noiseBtnsSelected");
    }

    noiseBtns[index].classList.add("noiseBtnsSelected");

    //Update description
    const description = noiseDescriptions[index];
    descriptionTitle.textContent = description.title;
    descriptionText.textContent = description.description;
}

//Volume
const volumeSlider = document.getElementById("volumeSlider");
const volumeInput = document.getElementById("volumeInput");

volumeSlider.addEventListener('input', function() {
    SetVolume(volumeSlider.value);
});

volumeInput.addEventListener('input', function() {
    SetVolume(volumeInput.value);
});


function SetVolume(volume) {
    state.volume = parseInt(volume);
    volumeSlider.value = volume;
    volumeInput.value = volume;
    gainNode.gain.value = state.volume / 100;
}

//Sampling Rate
const samplingRateInput = document.getElementById("samplingRateInput");
const samplingRateSlider = document.getElementById("samplingRateSlider");
const samplingRateSelection = document.getElementById("samplingRateSelection");
const samplingRateSelectionOptions = samplingRateSelection.getElementsByTagName("button")
const samplingRateExpandToggle = document.getElementById("samplingRateExpandToggle");

//Sampling Rate Selection Toggle
samplingRateExpandToggle.addEventListener('click', function() {
    if(samplingRateExpandToggle.classList.contains("samplingRateExpandToggleOn")) {
        samplingRateExpandToggle.classList.remove("samplingRateExpandToggleOn");
        samplingRateExpandToggle.classList.add("samplingRateExpandToggleOff");
        samplingRateExpandToggle.textContent = "+";

        samplingRateSelection.classList.add("samplingRateSelectionCollapsed");
    } else {
        samplingRateExpandToggle.classList.remove("samplingRateExpandToggleOff");
        samplingRateExpandToggle.classList.add("samplingRateExpandToggleOn");
        samplingRateExpandToggle.textContent = "-";

        samplingRateSelection.classList.remove("samplingRateSelectionCollapsed");
    }
});
samplingRateExpandToggle.classList.add("samplingRateExpandToggleOff");
samplingRateSelection.classList.add("samplingRateSelectionCollapsed");

//Sampling Rate Selection List
for(let i = 0; i < samplingRateSelectionOptions.length; i++) {
    samplingRateSelectionOptions[i].addEventListener('click', function() {
        SetSamplingRate(samplingRateSelectionOptions[i].value);
    });
}

//Sampling Rate Input
samplingRateInput.addEventListener('input', function() {
    SetSamplingRate(samplingRateInput.value);
});

//Sampling Rate Slider
samplingRateSlider.addEventListener('input', function() {
    SetSamplingRate(samplingRateSlider.value);
});

function SetSamplingRate(samplingRate) {
    state.samplingRate = parseInt(samplingRate);
    for(let i = 0; i < samplingRateSelectionOptions.length; i++) {
        if(samplingRateSelectionOptions[i].value == samplingRate) {
            samplingRateSelectionOptions[i].classList.add("samplingRateSelected");
        } else {
            samplingRateSelectionOptions[i].classList.remove("samplingRateSelected");
        }
    }

    samplingRateInput.value = samplingRate;
    samplingRateSlider.value = samplingRate;
}

//Duration
const durationSlider = document.getElementById("durationSlider");
const durationInput = document.getElementById("durationInput");

durationSlider.addEventListener('input', function() {
    SetDuration(durationSlider.value);
});

durationInput.addEventListener('input', function() {
    SetDuration(durationInput.value);
});

function SetDuration(duration) {
    state.duration = parseFloat(duration);
    durationSlider.value = duration;
    durationInput.value = duration;
}

//Visual Settings
const showWaveformToggle = document.getElementById('showWaveformToggle');
const showSpectrogramToggle = document.getElementById('showSpectrogramToggle');

showWaveformToggle.addEventListener('click', function () {
    if(showWaveformToggle.checked) {
        waveformCanvas.classList.remove("hideWaveformDisplay");
    } else {
        waveformCanvas.classList.add("hideWaveformDisplay");
    }
});

showSpectrogramToggle.addEventListener('click', function (){
    if(showSpectrogramToggle.checked) {
        spectrogramCanvas.classList.remove("hideSpectrogramDisplay");
    } else {
        spectrogramCanvas.classList.add("hideSpectrogramDisplay");
    }
});

//Draw
function draw() {
    requestAnimationFrame(draw);
    waveformDraw();
    if(getRMSVolume() > 0.001){
        spectrogramDraw();
    }
    playbackDraw();
}

//Server Check
let serverReady = false;
async function pingServer() {
    while(!serverReady) {
        try {
            const response = await fetch(serverURL + "/api/health");
            if(response.ok) {
                setServerReady(true);
            }
        } catch(error) {
            // still waking up, wait 30 seconds and try again
        }

        if(!serverReady) {
            await new Promise(resolve => setTimeout(resolve, 30000));
        }
    }
}

const serverConnectionNotification = document.getElementById("serverConnectionNotification");
function setServerReady(ready) {
    serverReady = ready;
    if(ready) {
        generateNoiseBtn.disabled = false;
        generateNoiseBtn.classList.remove("inactiveGenerateNoiseBtn");
                serverConnectionNotification.classList.add("hideServerConnectionNotification");
    } else {
        generateNoiseBtn.disabled = true;
        generateNoiseBtn.classList.add("inactiveGenerateNoiseBtn");
        serverConnectionNotification.classList.remove("hideServerConnectionNotification");
    }
}

//Initializations
setServerReady(false);
pingServer();
SetNoiseSelection(state.noiseType);
SetVolume(state.volume);
SetSamplingRate(state.samplingRate);
SetDuration(state.duration);

draw();